// config/admin-navigation.ts

import {
  LayoutDashboard,
  Activity,
  Building2,
  Users,
  Network,
  CreditCard,
  FileCheck,
  Settings,
  Server,
  Link,
  FileText,
  Shield,
  Stethoscope,
  UserCircle,
  FileSpreadsheet,
  Brain,
  ClipboardList,
  ActivitySquare,
  HeartPulse,
  CheckSquare,
  Hospital,
  Bed,
  Users as StaffIcon,
  Stethoscope as ClinicIcon,
  Calendar,
  Briefcase,
  Package,
  DollarSign,
  BarChart,
  UserCheck,
  NotepadText,
} from "lucide-react";

import type { UserRole, NavigationItem } from "./type";

// ─── Navigation record ──────────────────────────────────────────
export const adminNavigation: Record<UserRole, NavigationItem[]> = {
  ceo: [
    {
      name: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
      id: "dashboard",
      roles: ["ceo"],
    },
    {
      name: "Analytics",
      href: "/dashboard/analytics",
      icon: Activity,
      id: "analytics",
      roles: ["ceo"],
    },
    {
      name: "Verification",
      href: "/dashboard/verification",
      icon: UserCheck,
      id: "verification",
      roles: ["ceo"],
    },
    {
      name: "Referral Codes",
      href: "/dashboard/referrals",
      icon: Link,
      id: "referrals",
      roles: ["ceo"],
    },
    {
      name: "Doza Centers",
      href: "/dashboard/centers",
      icon: Building2,
      id: "dozaCenters",
      roles: ["ceo"],
    },
    {
      name: "Doza Medics",
      href: "/dashboard/medics",
      icon: Stethoscope,
      id: "dozaMedics",
      roles: ["ceo"],
    },
    {
      name: "Doza Users",
      href: "/dashboard/users",
      icon: Users,
      id: "users",
      roles: ["ceo"],
    },
    {
      name: "Network",
      href: "/dashboard/network",
      icon: Network,
      id: "dozaNetwork",
      roles: ["ceo"],
    },
    {
      name: "Subscriptions",
      href: "/dashboard/subscriptions",
      icon: CreditCard,
      id: "subscriptions",
      roles: ["ceo"],
    },

    {
      name: "Approvals",
      href: "/dashboard/approvals",
      icon: FileCheck,
      id: "approvals",
      roles: ["ceo"],
    },

    {
      name: "Audit Logs",
      href: "/dashboard/auditlogs",
      icon: FileText,
      id: "auditlogs",
      roles: ["ceo"],
    },
  ],
  cto: [
    {
      name: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
      id: "dashboard",
      roles: ["cto"],
    },
    {
      name: "System Health",
      href: "/dashboard/health",
      icon: Server,
      id: "health",
      roles: ["cto"],
    },
    {
      name: "API Management",
      href: "/dashboard/api",
      icon: Link,
      id: "api",
      roles: ["cto"],
    },
    {
      name: "Logs",
      href: "/dashboard/logs",
      icon: FileText,
      id: "logs",
      roles: ["cto"],
    },
    {
      name: "Security",
      href: "/dashboard/security",
      icon: Shield,
      id: "security",
      roles: ["cto"],
    },
  ],
  head_doctor: [
    {
      name: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
      id: "dashboard",
      roles: ["head_doctor"],
    },
    {
      name: "Medical Analytics",
      href: "/dashboard/medical-analytics",
      icon: Activity,
      id: "medical-analytics",
      roles: ["head_doctor"],
    },
    {
      name: "Patients",
      href: "/dashboard/patients",
      icon: UserCircle,
      id: "patients",
      roles: ["head_doctor"],
    },
    {
      name: "Medical Records",
      href: "/dashboard/medical-records",
      icon: FileSpreadsheet,
      id: "medical-records",
      roles: ["head_doctor"],
    },
    {
      name: "Prescriptions",
      href: "/dashboard/prescriptions",
      icon: NotepadText,
      id: "prescriptions",
      roles: ["head_doctor"],
    },
    {
      name: "Clinical Decision Support",
      href: "/dashboard/cds",
      icon: Brain,
      id: "cds",
      roles: ["head_doctor"],
    },
    {
      name: "Requisitions",
      href: "/dashboard/requisitions",
      icon: ClipboardList,
      id: "requisitions",
      roles: ["head_doctor"],
    },
  ],
  head_nurse: [
    {
      name: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
      id: "dashboard",
      roles: ["head_nurse"],
    },
    {
      name: "Nursing Analytics",
      href: "/dashboard/nursing-analytics",
      icon: ActivitySquare,
      id: "nursing-analytics",
      roles: ["head_nurse"],
    },
    {
      name: "Vitals Monitoring",
      href: "/dashboard/vitals",
      icon: HeartPulse,
      id: "vitals",
      roles: ["head_nurse"],
    },
    {
      name: "Task Management",
      href: "/dashboard/tasks",
      icon: CheckSquare,
      id: "tasks",
      roles: ["head_nurse"],
    },
    {
      name: "Patients",
      href: "/dashboard/patients",
      icon: UserCircle,
      id: "patients",
      roles: ["head_nurse"],
    },
  ],
  head_hospitals: [
    {
      name: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
      id: "dashboard",
      roles: ["head_hospitals"],
    },
    {
      name: "Hospital Analytics",
      href: "/dashboard/hospital-analytics",
      icon: BarChart,
      id: "hospital-analytics",
      roles: ["head_hospitals"],
    },
    {
      name: "Hospitals",
      href: "/dashboard/hospitals",
      icon: Hospital,
      id: "hospitals",
      roles: ["head_hospitals"],
    },
    {
      name: "Bed Occupancy",
      href: "/dashboard/bed-occupancy",
      icon: Bed,
      id: "bed-occupancy",
      roles: ["head_hospitals"],
    },
    {
      name: "Staff",
      href: "/dashboard/staff",
      icon: StaffIcon,
      id: "staff",
      roles: ["head_hospitals"],
    },
  ],
  head_clinics: [
    {
      name: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
      id: "dashboard",
      roles: ["head_clinics"],
    },
    {
      name: "Clinic Analytics",
      href: "/dashboard/clinic-analytics",
      icon: BarChart,
      id: "clinic-analytics",
      roles: ["head_clinics"],
    },
    {
      name: "Clinics",
      href: "/dashboard/clinics",
      icon: ClinicIcon,
      id: "clinics",
      roles: ["head_clinics"],
    },
    {
      name: "Appointments",
      href: "/dashboard/appointments",
      icon: Calendar,
      id: "appointments",
      roles: ["head_clinics"],
    },
    {
      name: "Staff",
      href: "/dashboard/staff",
      icon: StaffIcon,
      id: "staff",
      roles: ["head_clinics"],
    },
  ],
  head_operations: [
    {
      name: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
      id: "dashboard",
      roles: ["head_operations"],
    },
    {
      name: "Operations Analytics",
      href: "/dashboard/ops-analytics",
      icon: BarChart,
      id: "ops-analytics",
      roles: ["head_operations"],
    },
    {
      name: "Resource Allocation",
      href: "/dashboard/resources",
      icon: Briefcase,
      id: "resources",
      roles: ["head_operations"],
    },
    {
      name: "Staff Scheduling",
      href: "/dashboard/scheduling",
      icon: Calendar,
      id: "scheduling",
      roles: ["head_operations"],
    },
    {
      name: "Inventory",
      href: "/dashboard/inventory",
      icon: Package,
      id: "inventory",
      roles: ["head_operations"],
    },
  ],
  finance: [
    {
      name: "Dashboard",
      href: "/dashboard",
      icon: LayoutDashboard,
      id: "dashboard",
      roles: ["finance"],
    },
    {
      name: "Billing",
      href: "/dashboard/billing",
      icon: DollarSign,
      id: "billing",
      roles: ["finance"],
    },
    {
      name: "Financial Reports",
      href: "/dashboard/financial-reports",
      icon: BarChart,
      id: "financial-reports",
      roles: ["finance"],
    },
    {
      name: "Subscriptions",
      href: "/dashboard/subscriptions",
      icon: CreditCard,
      id: "subscriptions",
      roles: ["finance"],
    },
  ],
};

export function getAdminNavigation(role: UserRole): NavigationItem[] {
  return adminNavigation[role] || [];
}
